name: Trigger Profile Update

on:
  page_build

jobs:
  trigger-my-profile-update:
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch event to Profile Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/Siriusq/Siriusq/dispatches \
        --data '{"event_type": "update-my-profile"}'
